### ISSUE TITLE
can  show me the end result in the form of video or each other

### ISSUE THREAD

**Issue by itsnaini** [jbboin/opencv-skeleton-android#1]
i don't know the end reult. can you show it? thank you...

**Comment by jbboin** [comment]
Hi, I just added the .apk to the repository. You can run it without having to build the project to have a preview of the result. Hope this helps!

**Comment by itsnaini** [comment]
​
Thank you for responding quickly. I want to ask again whether the end
result like this ? is almost equal to the edge detection ?
​

2016-06-03 0:06 GMT+07:00 Jean-Baptiste Boin notifications@github.com:

**Comment by jbboin** [comment]
The point was just to have a basic setup using real-time OpenCV processing that can be used for other projects. Currently only Canny edge detection is performed but other operations are possible (the function processFrame in jni/native.cpp contains the logic for that).
